apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: hello
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hello
        imagePullPolicy: Always
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev